### PR TITLE
Add some features and transform to an maven project

### PR DESCRIPTION
**Pull request by alansferreira**
1 - Phanton fix and invoque own class and super class properties and methods
2 - some fixes
3 - more filters like "in", "distinct" and re-type "select" return value

### CODE REVIEW

**Comment by JalalSordo** [comment]
can I get it ?

**Comment by alansferreira** [comment]
of corse!

**Comment by JalalSordo** [comment]
I used your fork already, this coolection lib comes very handy when you are doing InMemory Data providers.

**Comment by wagnerandrade** [comment]
Oh sorry folks... I just saw all that work! I was in a vacation... Let me take a look on that.

**Comment by willman137** [comment]
Hey, So I'm using collections in a project for my company. It's a great concept, but some of the actual functionality I am trying to program is already in this pull request. Like unique() and type returns. Any info on a date when some of these features will be pushed into a new version?

**Comment by wagnerandrade** [comment]
Hey dude... I'm alive... Sorry!

Do you wan't to keep this ship going, @alansferreira?

**Comment by alansferreira** [comment]
Hi, bro.. i´m adding features, it´s a cool project. In my work we use old java version with no lambda.
I´m maintain a secondary repo, forking and updating my fork.

**Comment by alansferreira** [comment]
If you do not want to keep the project no problem! I have a copy and took the liberty of renaming the packages to 'org.simple'.

Thank´s for project idea!

**Pull request closed without merging**
